name: kellerman
favicon: null
layout_spectrum: 0.5271078930236399
typography_spectrum: 0.7933793927077204
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.31435571564361453
  lightness: 0.2713941701222211
  saturation: 0.24870201223529875
  rhythmicContrast: 0.34682914847508073
purpose: []
